repo: 'responsive-banner'
canvasCourse: 'web-dev-4'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    outline: true
    has:
      - ['link[href*="modules.css"] + link[href*="type.css"]', 'The `modules.css` file must come before the `type.css` file']
      - ['link[href*="type.css"] + link[href*="main.css"]', 'The `type.css` file must come before the `main.css` file']
      - 'div'
      - 'img.img-flex'
      - 'a.btn'
    search:
      - 'The Planet Earth'
      - 'An amazingly species rich'
      - 'Book a star cruise'
      - 'push-'
      - 'gutter-'
      - 'pad-'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'font-family', 'Georgia, serif']
    search:
      - '#fff'
      - '#efefef'
      - '#97a49b'
      - '#495562'
      - 'rgba\(73, 85, 98'
      - 'max-width: 50em'
      - 'max-width: 25em'
      - 'max-height: 500px'
      - 'background-image: linear-gradient'
    searchNot:
      - ['@media.+\(.*max-width', 'Media queries with `max-width` should not be used — use `min-width` instead']
  - path: 'css/type.css'
    valid: true
    bestPractices: true
    search:
      - ['https://typografier.web-dev.tools/#0,100,1.3,1.067,0;38,110,1.4,1.125,1;60,120,1.5,1.125,1;90,130,1.5,1.125,1', 'The `type.css` should be generated with Typografier’s default settings']
  - path: 'css/modules.css'
    valid: true
    bestPractices: true
    search:
      - ['https://modulifier.web-dev.tools/#responsive;images;list-group;embed;media-object;icons;hidden;positioning;nice-lists;buttons;forms;accessibility;print', 'Select all the different modules when adding Modulifier.']

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('a.btn');
        let oldBg = css(link).backgroundColor;

        hover('a.btn', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the button doesn’t change when hovered')
          pass();
        });
